name: "1.3 - [Iedereen] Requirement - Eis"
description: "Voor: Alle teams | Doel: Requirement vastleggen"
title: "[REQUIREMENT] "
labels: ["requirement", "needs-review"]
projects: ["Forta-nl/2"]
assignees:
  -
body:
  - type: markdown
    attributes:
      value: |
        ## Requirement

        Dit formulier wordt gebruikt voor **Requirements.

  

  - type: dropdown
    id: requirement-type
    attributes:
      label: Type Requirement
      description: Wat voor soort requirement is dit?
      options:
        - User
        - AI/LLM requirement
        - System
        - Compliance
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Beschrijving Requirement
      description: Beschrijf de voorgestelde requirement in detail
      placeholder: Leg de context uit, beschrijf het probleem en de doelstellingen van deze requirement?
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Achterliggende gedachte
      description: Waarom is deze requirement nodig?
      placeholder: |
        - Klinisch?
        - Markt?
        - Compliance requirement?
        - Kwaliteit?
        - Gebruiksgemak?
    validations:
      required: true


  - type: dropdown
    id: priority
    attributes:
      label: Prioriteit
      options:
        - "Must"
        - "Should have"
        - "Could have"
      default: 2
    validations:
      required: true

  - type: dropdown
    id: source
    attributes:
      label: Bron
      options:
        - "Forta AI team"
        - "Klankbordgroep"
        - "Markt/Extern"
        -  "Anders-Forta"
      default: 2
    validations:
      required: true
 

  - type: markdown
    attributes:
      value: |
        ---

        **Na indienen:**
        ✨ Dit issue genereert automatisch **5 sub-issues** die stap-voor-stap doorlopen worden.

        Elk sub-issue heeft zijn eigen velden en verantwoordelijk team.
